### ISSUE TITLE
Export alfredsnippets into other formats?

### ISSUE THREAD

**Issue by tigecyclindamycin** [derickfay/import-alfred-snippets#3]
Hi there, thanks for the helpful guide with instructions for exporting .csv into .alfredsnippets. Unfortunately, I'm actually looking for a solution for the reverse, as I want to move my snippets to a better text expansion service. May I ask if it's possible to export .alfredsnippets into .csv? How may I go about it?

**Comment by derickfay** [comment]
> ".alfredsnippets, like  .alfredworkflow, is just a renamed .zip file. Unzip it and you’ll find all your snippets inside, in a clear JSON format."

from https://www.alfredforum.com/topic/11184-export-snippets-into-other-formats/

**Comment by tigecyclindamycin** [comment]
Thanks for the reply. How do I get it from JSON to CSV?
